version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    # optional but recommended
    open-pull-requests-limit: 10

    # group minor updates
    groups:
      minor-and-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
